name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright E2E tests
        run: npm run test:e2e
      - name: Trigger deployment
        id: deploy
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notify on success
        if: steps.deploy.outcome == 'success'
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{
                \"content\": \"✅ Deployment succeeded!\nCommit: ${{ github.sha }}\nMessage: ${{ github.event.head_commit.message }}\"
              }" \
              "${{ secrets.DISCORD_WEBHOOK }}"
      - name: Notify on failure
        if: steps.deploy.outcome == 'failure'
        run: |
          curl -H "Content-Type: application/json" \
              -X POST \
              -d "{
                \"content\": \"❌ Deployment failed!\nCommit: ${{ github.sha }}\nMessage: ${{ github.event.head_commit.message }}\"
              }" \
              "${{ secrets.DISCORD_WEBHOOK }}"
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }} 
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main