name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright E2E tests
        run: npm run test:e2e
      - name: Trigger deployment
        id: deploy
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_I }}?key=${{ secrets.RENDER_API_KE }}
      - name: Get current time
        id: now
        run: echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Notify on success
        uses: tsickert/discord-webhook@v7.0.0
        if: steps.deploy.outcome == 'success'
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "🚀 A new version of Pokedex deployed" 
          embed-description: "🚀 To https://full-stack-open-pokedex-b2lm.onrender.com/ by errami01"
          embed-timestamp: "At ${{ steps.now.outputs.time }}"
          embed-color: 3066993
      - name: Notify on failure
        if: steps.deploy.outcome == 'failure'
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "❌ Build failed!"
          embed-description: "Commit: ${{ github.sha }} by errami01 broke the build"
          embed-timestamp: "At ${{ steps.now.outputs.time }}"
          embed-color: 15158332
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }} 
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main